name: LanguageAPI
main: net.kettlemc.language.spigot.SpigotAdapter
version: 1.2
api-version: 1.13
depend: [Skript]
author: LeStegii
description: KettleMC Language Plugin
commands:
  language:
    aliases:
      - languages
      - lang
      - sprache